#!/usr/bin/python
import sys
import argparse
import JenkHandlers
import os.path
import json

with open(os.path.expanduser('~/.jenk')) as fp:
    data = json.load(fp)

url = data['url']

parser = argparse.ArgumentParser()
parser.add_argument('filter', type=str, nargs='*')
parser.add_argument('-b', type=int, dest='show_builds', default=0, action='store')
parser.add_argument('-c', type=int, dest='console_log', default=None, action='store')

args = parser.parse_args()

JenkHandlers.handle(url, args.show_builds, args.filter, args.console_log)
